export const projects = [
  {
    title: 'OMNIFOOD',
    description: "Using HTML, CSS and Javascript implemented The smart 365-days-per-year food subscription that will make you eat healthy again.",
      image: '/images/omnifood.jpg',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://omnifood.dev',
    visit: 'https://github.com/Ivandamien/omnifood',
    id: 0,
  },
  {
    title: 'Forkify',
    description:"While learning Javascript tried rebuilding this recipe application from scratch though not responsive on mobile applications. You can search any recipe and upload as well",
    image: '/images/forkify.jpg',
    tags: ['Scss', 'JavaScript', 'Parcel', 'Ajax'],
    source: 'https://forkify-v6.netlify.app/',
    visit: 'https://github.com/Ivandamien/forkify-test',
    id: 1,
  },
  {
    title: 'Natours',
    description: "This is a full stack application. Its a web app for planning, booking and reviewing tours.Payment checkout using stripe has been intergrated with all secured authentications",
      image: '/images/natours.jpg',
      tags: ['React', 'NodeJs', 'MongoDb','Stripe','Express'],
    source: 'https://natours-g12a.onrender.com/',
    visit: 'https://github.com/Ivandamien/natours',
    id: 2,
  },
  {
    title: 'Shortly',
    description: "This is a simple landing page for a link shortening website. The design was inspired by frontendmentor.io",
    image: '/images/shortly.jpg',
    tags: ['HTML', 'Tailwindcss', 'Javascript'],
    source: 'https://shortly-v2.netlify.app/',
    visit: '#',
    id: 3,
  },
  {
    title: 'SuperBANK',
    description: "This is a material UI Digital Payment LandingPage designed by Andika Bagass for One Week Wonders.I rebuild it from scratch using React and optimized it to be mobile responsive",
    image: '/images/hoobank.jpg',
    tags: ['React', 'Tailwindcss', 'Javascript','Figma','vite'],
    source: 'https://superbank.vercel.app/',
    visit: 'https://github.com/Ivandamien/superbank',
    id: 3,
  },
  {
    title: 'Gpt3',
    description: "This is a landing page for GPT3-Openai. I rebuild this site from scratch using React.Its responsive on all devices. The figma design was inspired by dribbble.com",
    image: '/images/gpt.jpg',
    tags: ['React', 'CSS', 'Javascript'],
    source: 'https://gpt-rosy.vercel.app/',
    visit: 'https://github.com/Ivandamien/gpt',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2020, text: 'Worked as a freelance developer', },
  { year: 2021, text: 'Improving my skills and keeping upto date with the current technologies', },
  { year: 2022, text: 'Shared some my projects with the world', },
  { year: 2023, text: 'Joining tech communities and working on projects', },
];